// <auto-generated />
namespace WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MAP_HOCSINH_TO_LOPHOC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAP_HOCSINH_TO_LOPHOC));
        
        string IMigrationMetadata.Id
        {
            get { return "201601170530039_MAP_HOCSINH_TO_LOPHOC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
