// <auto-generated />
namespace WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UPDATEDATABASE07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UPDATEDATABASE07));
        
        string IMigrationMetadata.Id
        {
            get { return "201601201639336_UPDATE-DATABASE-07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
